spring:
  application:
    name: "Azure Service Bus Test"

cloud:
  azure:
    servicebus:
      namespace: ddtm-topic-test
      consumer:
        test-topic2:
          connectionString: ${CONNECTION_STRING}
          maxConcurrentCalls: 5
      producer:
        test-topic2:
          connectionString: ${CONNECTION_STRING}